### PR TITLE
Add a new guest article with How I managed to get scikit-learning working as AWS Lambda layer

### PR DESCRIPTION
**Pull request by pmayd**
It got longer than expected, but I like explaining things step by step, clearly and so that everyone can follow and no information is missing, if you actually need things to get working. But we could make a new article from this...However, here is my addition and promised section!

### CODE REVIEW

**Comment by bbelderbos** [comment]
Thanks @pmayd, actually yes I think it's better to make it a part II / new article. So we can push it out as new, and link to it from the first article. And list you as the author! 

Could you do that please? Also please make a bio section on the guests page (content/pages/guests.md == https://pybit.es/pages/guests)

Thanks!
Bob

**Comment by pmayd** [comment]
@bbelderbos Done as asked, I hope I changed the right files and did everything as I should, first timer...

**Comment by pmayd** [comment]
Right now make html does not create a html file for my article, but I don't get any error messages, so likely I missed something

**Comment by pmayd** [comment]
Ok, forgot the `md` file ending, article is now rendered correctly!

**Comment by bbelderbos** [comment]
Sweet thanks @pmayd I will publish it later today.

**Comment by bbelderbos** [comment]
@pmayd can you confirm the merged in PR counts now that the repo has the Hacktoberfest label?

**Comment by pmayd** [comment]
Right now it is still in review mode, but I think the status will change only after the review period that is given by hacktoberfest, and this period seems to be 11 or 12 days? Originally, it was 5 but they seem to have prolonged it

**Pull request merged**
