### PR TITLE
created 80% version of the article: GitHub-project-boards

### PR DESCRIPTION
**Pull request by Zaubeerer**
-> how to handle images?
-> feedback on content and style?

### CODE REVIEW

**Comment by Zaubeerer** [comment]
Hey @pybites, 

after our discussion today, I just directly started writing and can now present you this first draft of the GitHub projects blog article.

What do you think about content and style?

How do I have to store images such that they get correctly rendered in the blog posts?

Cheers!

Robin

**Comment by bbelderbos** [comment]
Thanks @Zaubeerer, let me get that up. I will put / link images in content/images/

I guess I can reuse your bio from your website?

**Comment by pybites** [comment]
Could you revive this link please? https://github.com/Zaubeerer/github_board_tutorial

**Comment by pybites** [comment]
image

Happy to add, but it links to your site for more

**Comment by Zaubeerer** [comment]
> Could you revive this link please? https://github.com/Zaubeerer/github_board_tutorial

Does it work now? Was private but I made it public again :)

**Comment by bbelderbos** [comment]
yep works, thanks

**Pull request merged**
