### PR TITLE
Type Hints

### PR DESCRIPTION
**Pull request by pmayd**
This is my guest blog article about type hints. 

I worked a lot on the early draft and the article is now nearly complete with regard of its content. 
I start with an introduction to type hints and what they are and how they work in python. I go on to show example of where to best use type hints and why (so how do you benefit from it). I finish with a section about type checking with mypy and within visual studio code.

Right now the only section that is missing is the recommendations section.

### CODE REVIEW

**Comment by pmayd** [comment]
@bbelderbos I thinkl the article is in a state that were you can start reading and give some feedback about the scope and depth. It is much longer than I had anticipated, but I still think the content is right for our purpose and the examples are worthwile, but I can keep it shorter of course.

**Comment by bbelderbos** [comment]
Sweet @pmayd 
Tomorrow with fresh coffee
Thanks for writing it, will ve very helpful!

**Comment by pmayd** [comment]
Is it bad if I cannot create the html? I am not able to successfully run `make html` I always get the following error:
CRITICAL: not all arguments converted during string formatting
make: *** [html] Fehler 1

**Comment by pmayd** [comment]
I improved the article a lot refactored sections and added more examples. I think the main body of the article is now ready and the only thing that is missing are the recommendations at the end. Aim to finish it at the weekend

**Comment by bbelderbos** [comment]
@pmayd excellent article, liked it a lot. Let me know when done and I merge and render and review it locally as html. Thanks!

**Comment by pmayd** [comment]
I finished the recommendations section! So my article is officially written. But I want to let a friend do a proof reading. So if you want to add some comments or know someone who wants to do a review please add them

**Comment by bbelderbos** [comment]
Awesome, thanks. I can review it again (although first read I really liked it, it's great), I'll ask someone else as well ...

**Comment by pmayd** [comment]
Thank you, Bob. Then let's say we publish it next Monday :)

**Comment by bbelderbos** [comment]
@pmayd I am merging this in so I can render it locally for review, this does not publish it to our blog yet.
We can do pending changes with a new PR ...

**Comment by pmayd** [comment]
Sure thanks Bob

**Pull request merged**
