### PR TITLE
Using python to check for file changes in excel

### PR DESCRIPTION
**Pull request by ryancheley**
I wrote a thing that I hope you enjoy about using Python and Pandas to compare excel files.

### CODE REVIEW

**Comment by bbelderbos** [comment]
Thanks @ryancheley, getting it up.

**Comment by bbelderbos** [comment]
Nice article. Only thing I would change is the except/pass as it's considered an anti-pattern.
Cheers
Bob

**Comment by bbelderbos** [comment]
And it's probably better to open a file with the "with" statement (context manager)

**Comment by ryancheley** [comment]
@bbelderbos thanks for the feedback. Also, like the new look of the Blog!

**Pull request merged**
