### PR TITLE
finished guest article for Pybites Blog

### PR DESCRIPTION
**Pull request by JB0925**
Feel free to modify the article as needed!

### CODE REVIEW

**Comment by bbelderbos** [comment]
Thanks Jesse, do you have the code as well? And can you include a one paragraph bio for the guests page?

**Comment by bbelderbos** [comment]
Thanks @JB0925 I will publish it later today.

**Comment by bbelderbos** [comment]
@JB0925 done: https://pybit.es/python-homework.html > nice use case. Maybe embedding some code or adding a photo would be nice. Also please follow https://pybit.es/guest-howto-write-guest-posts.html next post, I did have to do some moving around and formatting. Thanks for sharing this cool story.

**Comment by JB0925** [comment]
Hey Bob, you're welcome. I tried to follow it, but my computer was being being weird about markdown, so I was doing the best I could.

**Pull request merged**
